export interface UserResponse {
  user: User;
  token: string;
}

export interface User {
  createdAt: string;
  updatedAt: string;
  email: string;
  id: string;
  name: string;
}

export interface CategoryResponse {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
}

export interface AuthenticateUserInput {
  email: string;
  password: string;
}

export interface newUserInput {
  name: string;
  email: string;
  password: string;
}

export interface BudgetResponse {
  id: string;
  name: string;
  amount: number;
  remaining: number;
  createdAt: string;
  updatedAt: string;
}

// Generated by https://quicktype.io

export interface BudgetIDResponse {
  getBudget: GetBudget;
}

export interface GetBudget {
  id: string;
  amount: number;
  remaining: number;
  name: string;
  categories: Category[];
  createdAt: string;
}

export interface Category {
  id: string;
  name: string;
  transactions: Transaction[];
  createdAt: string;
}

export interface Transaction {
  id: string;
  amount: number;
  createdAt: string;
}

export interface ChartData {
  name: string;
  transaction: number;
  remaning: number;
}
